$ErrorActionPreference = "Stop"

$root = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
$patchDir = Join-Path $root "mods\patches\cnMissionManager-forcecomplete"
$outFile = Join-Path $PSScriptRoot "PatchedDonor.g.cs"

function Get-MethodBody($file) {
    $lines = Get-Content $file
    $start = 0
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^\s*(private|public)\s+') {
            $start = $i
            break
        }
    }
    return ($lines[$start..($lines.Count - 1)] -join "`n")
}

function Get-ForceCompleteMethod($file) {
    $lines = Get-Content $file
    $start = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^\s*public\s+void\s+ForceCompleteCurrentTask\s*\(') {
            $start = $i
            break
        }
    }
    if ($start -lt 0) {
        throw "ForceCompleteCurrentTask not found in $file"
    }
    $depth = 0
    $started = $false
    $end = $start
    for ($i = $start; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -match '\{') {
            $depth++
            $started = $true
        }
        if ($started -and $line -match '\}') {
            $depth--
            if ($depth -eq 0) {
                $end = $i
                break
            }
        }
    }
    return ($lines[$start..$end] -join "`n")
}

$memberLines = Get-Content (Join-Path $patchDir "add-class-members-compile-paste.txt")
$memberStart = -1
for ($i = 0; $i -lt $memberLines.Count; $i++) {
    if ($memberLines[$i] -match '^\s*public\s+partial\s+class\s+cnMissionManager') {
        $memberStart = $i + 1
        break
    }
}
if ($memberStart -lt 0) {
    throw "cnMissionManager partial class not found in add-class-members-compile-paste.txt"
}
while ($memberStart -lt $memberLines.Count -and $memberLines[$memberStart] -match '^\s*$') {
    $memberStart++
}
if ($memberStart -lt $memberLines.Count -and $memberLines[$memberStart] -match '^\s*\{') {
    $memberStart++
}
$memberEnd = $memberLines.Count - 1
while ($memberEnd -gt $memberStart -and $memberLines[$memberEnd] -match '^\s*$') {
    $memberEnd--
}
if ($memberEnd -gt $memberStart -and $memberLines[$memberEnd] -match '^\s*\}') {
    $memberEnd--
}
$membersText = ($memberLines[$memberStart..$memberEnd] -join "`n")

$methods = @(
    (Get-ForceCompleteMethod (Join-Path $patchDir "step6-ForceComplete-block.cs"))
)

$methodsText = ($methods -join "`n`n")

$content = @"
// <auto-generated by build-donor.ps1 — do not edit>
using System;
using System.Collections;
using System.Runtime.InteropServices;
using UnityEngine;

public partial class cnMissionManagerV2Donor
{
$membersText

$methodsText
}
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8
Write-Host "Generated $outFile"
