// <auto-generated by build-donor.ps1 â€” do not edit>
using System;
using System.Collections;
using System.Runtime.InteropServices;
using UnityEngine;

public partial class cnMissionManagerV2Donor
{
	private void EmitDocCompletePacket(cnMissionNode task)
	{
		if (task == null || task.GetMe() == null)
		{
			return;
		}
		for (int i = 0; i < 3; i++)
		{
			task.m_aiCurrentRemainEnemyNum[i] = 0;
			task.m_aiCurrentRemainItemNum[i] = 0;
		}
		MissionElement me = task.GetMe();
		if (me.m_iSTGrantTimer > 0 || me.m_iCSUCheckTimer > 0)
		{
			task.m_fRemainTime = 0f;
			task.m_fLifeTime = 0f;
		}
		bool err = false;
		if (me.m_iRequireInstanceID == 12)
		{
			if (this.ownstatus == null || this.ownstatus.iInsMapNum != 12)
			{
				err = true;
			}
		}
		int npc = 0;
		if (!err && me.m_iHTerminatorNPCID != 0)
		{
			npc = me.m_iHTerminatorNPCID;
			if (!this.pNpcContainer.SearchTableID(npc))
			{
				npc = 0;
			}
		}
		this.RequestTaskComplete(me.m_iHTaskID, npc, err);
	}

	// FCT hotkey splice â€” quotas already cleared; npc/err only (saves 1520640 slot)
	private void EmitDocCompletePacketHotkey(cnMissionNode task)
	{
		if (task == null || task.GetMe() == null)
		{
			return;
		}
		MissionElement me = task.GetMe();
		bool err = false;
		if (me.m_iRequireInstanceID == 12)
		{
			if (this.ownstatus == null || this.ownstatus.iInsMapNum != 12)
			{
				err = true;
			}
		}
		int npc = (!err) ? me.m_iHTerminatorNPCID : 0;
		this.RequestTaskComplete(me.m_iHTaskID, npc, err);
	}

	// EndSucc inline splice only â€” minimal RTC to save 1520640 slot
	private void EmitDocCompletePacketSlim(cnMissionNode task)
	{
		if (task == null || task.GetMe() == null)
		{
			return;
		}
		MissionElement me = task.GetMe();
		this.RequestTaskComplete(me.m_iHTaskID, 0, false);
	}

	private void TryForceCompleteChainTask(cnMissionNode task)
	{
		if (task == null || task.GetMe() == null)
		{
			this.m_iloopTemp = 0;
			return;
		}
		if (this.m_iloopTemp >= 16)
		{
			this.m_iloopTemp = 0;
			return;
		}
		MissionElement me = task.GetMe();
		Logger.Log("ForceCompleteV2: chain doc-complete task " + me.m_iHTaskID.ToString());
		this.m_iloopTemp++;
		this.EmitDocCompletePacket(task);
	}

	// phase: 0=EndFail 1=EndSucc 2=StartFail 3=StartSucc
	private bool ForceCompleteChainHook(int phase, cnMissionNode task, int arg)
	{
		if (this.m_iloopTemp <= 0)
		{
			return false;
		}
		if (phase == 2 || phase == 3)
		{
			task = this.GetTask(arg);
			if (task == null || task.GetMe() == null)
			{
				return phase == 2;
			}
			if (phase == 2)
			{
				Logger.Log("ForceCompleteV2: instance start fail complete task " + arg.ToString());
				this.EmitDocCompletePacket(task);
				return false;
			}
			MissionElement me = task.GetMe();
			if (0 < me.m_iRequireInstanceID)
			{
				Logger.Log("ForceCompleteV2: instance zone complete task " + me.m_iHTaskID.ToString());
				this.EmitDocCompletePacket(task);
			}
			return false;
		}
		if (task == null || task.GetMe() == null)
		{
			this.m_iloopTemp = 0;
			return true;
		}
		if (phase == 0)
		{
			if (arg == 13)
			{
				this.m_iloopTemp = 0;
				return true;
			}
			if (arg == 1 || arg == 11 || arg == 12)
			{
				Logger.Log("ForceCompleteV2: retry task " + task.GetMe().m_iHTaskID.ToString() + " err " + arg.ToString());
				this.EmitDocCompletePacket(task);
				return true;
			}
			this.m_iloopTemp = 0;
			return false;
		}
		cnMissionNode next = null;
		if (0 < task.GetMe().m_iSUOutgoingTask)
		{
			next = this.GetTask(task.GetMe().m_iSUOutgoingTask);
		}
		if (next == null)
		{
			next = this.GetNextTaskNode(task);
		}
		if (next != null && next.GetMe() != null)
		{
			Logger.Log("ForceCompleteV2: advance to task " + next.GetMe().m_iHTaskID.ToString());
			this.TryForceCompleteChainTask(next);
			return true;
		}
		Logger.Log("ForceCompleteV2: chain finished");
		this.m_iloopTemp = 0;
		return true;
	}

	public void ForceCompleteCurrentTask()
	{
		Logger.Log("ForceCompleteV2: patch build 2026-06-09-doc504h");
		cnMissionNode target = this.SelectMissionTask;
		if (target == null || target.GetMe() == null)
		{
			target = this.GetSelectedActiveMission();
		}
		if (target == null || target.GetMe() == null)
		{
			if (this.m_ActivateMissionList.Count > 0)
			{
				target = (cnMissionNode)this.m_ActivateMissionList[this.m_ActivateMissionList.Count - 1];
			}
		}
		if (target == null || target.GetMe() == null)
		{
			return;
		}
		MissionElement me = target.GetMe();
		Logger.Log("ForceCompleteV2: hotkey target task " + me.m_iHTaskID.ToString());
		this.m_iloopTemp = 1;
		target.m_aiCurrentRemainEnemyNum[0] = 0;
		target.m_aiCurrentRemainEnemyNum[1] = 0;
		target.m_aiCurrentRemainEnemyNum[2] = 0;
		target.m_aiCurrentRemainItemNum[0] = 0;
		target.m_aiCurrentRemainItemNum[1] = 0;
		target.m_aiCurrentRemainItemNum[2] = 0;
		bool err = me.m_iRequireInstanceID == 12 && (this.ownstatus == null || this.ownstatus.iInsMapNum != 12);
		int npc = 0;
		if (!err && me.m_iHTerminatorNPCID != 0 && this.pNpcContainer.SearchTableID(me.m_iHTerminatorNPCID))
		{
			npc = me.m_iHTerminatorNPCID;
		}
		this.RequestTaskComplete(me.m_iHTaskID, npc, err);
	}
}
